### PR TITLE
Mysterious future

### PR DESCRIPTION
**Pull request by pallas**
Fixed up h264, IPv6, & FDK-AAC

### CODE REVIEW

**Comment by FD-** [comment]
This looks good, but I haven't yet tested it on an actual Pi. Sorry for the delay, hope to find time this weekend!

**Comment by FD-** [comment]
I'm seeing a Segfault when running this on a Pi Zero:

```
pi@raspberrypi(ro):~/rpiplay-inject/RPiPlay/build$ ./rpiplay -n "Inject"
Initialized server socket(s)
*** WARNING *** The program 'rpiplay' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Accepted IPv6 client on socket 16
Local: fe80:0000:0000:0000:02e0:4cff:fe36:01c1
Remote: fe80:0000:0000:0000:10d0:3ddf:b15b:9869
Segmentation fault
```

**Comment by pallas** [comment]
@FD- could you please get a backtrace? I'm happy to take a look but haven't been able to reproduce.

**Comment by FD-** [comment]
Sorry, should have included one in the first place:

```
Thread 8 "rpiplay" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb34fb3e0 (LWP 4402)]
0x0001e788 in raop_ntp_start ()
(gdb) backtrace
#0  0x0001e788 in raop_ntp_start ()
#1  0x0001bba0 in raop_handler_setup ()
#2  0x0001d1b4 in conn_request ()
#3  0x000250cc in httpd_thread ()
#4  0xb6c86494 in start_thread (arg=0xb34fb3e0) at pthread_create.c:486
#5  0xb69fc578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

I'll try if undoing the IPv6 changes fixes it.

**Comment by FD-** [comment]
Yeah, it's the IPv6 commit.

**Comment by pallas** [comment]
Ok, let's skip that one for now then.

**Pull request merged**
