### PR TITLE
Added cec support

### PR DESCRIPTION
**Pull request by geekpersonman**
Automatically turns off tv on startup, then turns on tv when a connection is made and turns tv back off when a connection is closed. Requires libcec-dev to be installed to compile, can be installed with "sudo apt install libcec-dev"

### CODE REVIEW

**Comment by geekpersonman** [comment]
also has a -c option do disable cec

**Comment by FD-** [comment]
Thanks for your PR! The reason why I haven't merged it yet is because I believe it would be cleaner if the cec code was all in the video renderer. The additional callback AFAICT wouldn't be necessary, since renderer_flush is called on connection end and start is when the first frame buffer comes in. If you want more explicit callbacks, I'd rather like adding connection_established and connection_destroyed (or similar) callbacks to raop_callbacks_t and have the renderer connect to these. I think the CEC code is rather renderer specific, so should be kept in the renderer. What do you think?

**Comment by geekpersonman** [comment]
That makes sense, I'll see if I can put the callbacks in the renderer instead in the next few days, I just put the callbacks where I did because the httpd was the first very obvious spot I could find where an airplay stream is started/ended, and I put the main cec code in the main RPiPlay file because the C++ interface to libcec appears to be a lot more fleshed out than the C interface and RPiPlay is the only C++ file in the project.

**Comment by FD-** [comment]
Just skimming through the libcec C++ functions you used, I found an equivalent for most of them (only the unload function seems irrelevant for C) in the [libcec C interface](https://github.com/Pulse-Eight/libcec/blob/master/include/cecc.h).

**Comment by pallas** [comment]
As an aside, I normally have a screensaver + pianobar running. It would be nice to have callback scripts for connect/disconnect, e.g. to killall SIGSTOP/SIGCONT those when rpiplay has a legitimate screen to show. Right now, I've got a script that polls for a CONNECTED TCP socket but it feels hacky.

**Comment by rcarmo** [comment]
@pallas seems like a great idea.

**Comment by pallas** [comment]
@rcarmo see the script I posted on Issue #82.

**Comment by alecsandes** [comment]
Hi, I would really like to have this option but honestly, I am lacking the knowledge to use this... How can I implement your work?

**Pull request closed without merging**
